# ----- WARINING -----
# The secret credentials provided below are intended for development purposes only.
# For real production environments, please utilize a secret management system.

version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psql_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psql_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rest:
    container_name: pg_postgrest
    image: postgrest/postgrest
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/psql_local
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: aefb19a0c33f0aaace954f7e53ecbe34c5adb28198daf054d5b162d7fcf10db5
    depends_on:
      - postgres

volumes:
  postgres_data:
