version: "3.8"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psql_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: psql_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rest:
    container_name: pg_postgrest
    image: postgrest/postgrest
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@postgres:5432/psql_local
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - postgres

volumes:
  postgres_data:
